Vagrant.configure("2") do |config|
  # Nom de la VM dans VirtualBox
  config.vm.define "naaliS"

  # Utilisation de la dernière version stable de Debian 12 (Bookworm)
  config.vm.box = "debian/bookworm64"

  # Configurer une IP statique pour la VM
  config.vm.network "private_network", ip: "192.168.56.110"

  # Configurer les ressources (mémoire et CPU)
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    vb.name = "naaliS"
    vb.memory = 1024
    vb.cpus = 2
  end

  # Provision avec un script shell pour installer K3s et déployer les applications
  config.vm.provision "shell", inline: <<-SHELL
    # Mise à jour des paquets et installation de curl
    apt-get update
    apt-get install -y curl

    # Installation de K3s (Kubernetes léger)
    curl -sfL https://get.k3s.io | sh -

    # Attendre que K3s soit opérationnel
    sleep 30

    # Importer les images Docker pour app1, app2, app3 dans containerd
    sudo ctr images import /vagrant/app1/app1-nginx.tar
    sudo ctr images import /vagrant/app2/app2-nginx.tar
    sudo ctr images import /vagrant/app3/app3-nginx.tar

    # Appliquer les fichiers de déploiement et de service pour chaque application
    kubectl apply -f /vagrant/app1/app1-deployment.yaml
    kubectl apply -f /vagrant/app1/app1-service.yaml
    kubectl apply -f /vagrant/app2/app2-deployment.yaml
    kubectl apply -f /vagrant/app2/app2-service.yaml
    kubectl apply -f /vagrant/app3/app3-deployment.yaml
    kubectl apply -f /vagrant/app3/app3-service.yaml

    # Appliquer le fichier Ingress pour configurer le routage des applications
    kubectl apply -f /vagrant/ingress.yaml
  SHELL

  # Partage du dossier local contenant les images Docker et fichiers YAML avec la VM
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end

